package com.example.whitefox.tracking.enums;

public enum GarmentStatus {

    TAGGED_AT_STORE,
    LOADED_ON_TRUCK,
    SENT_TO_HQ,
    RECEIVED_AT_HQ,

    OLD_QR_REMOVED,
    CLEANING_IN_PROGRESS,
    CLEANING_DELAYED,
    CLEANING_COMPLETED,
    OUTING_QR_ATTACHED,

    READY_FOR_STORE_DISPATCH,
    LOADED_FOR_STORE,
    SENT_TO_STORE,
    RECEIVED_AT_STORE_AFTER_PROCESSING,

    READY_FOR_CUSTOMER_PICKUP,
    OUT_FOR_DELIVERY,
    DELIVERED,

    LOST,
    DAMAGED
}