package com.example.whitefox.tracking.enums;

public enum GarmentStatus {
    TAGGED_AT_STORE,
    LOADED_FOR_HQ,
    DROPPED_AT_HQ,
    RECEIVED_AT_HQ,
    PROCESSING,
    PROCESSED_QR_REATTACHED,
    LOADED_FOR_STORE,
    DROPPED_AT_STORE,
    REPORTED_MISSING,
    READY_FOR_CUSTOMER_PICKUP,
    READY_FOR_DELIVERY,
    ASSIGNED_FOR_DELIVERY,
    OUT_FOR_DELIVERY,
    DELIVERED,
    LOST,
    DAMAGED
}