spring.datasource.url=jdbc:postgresql://localhost:5432/whitefox
spring.datasource.username=mahimahi
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=false

jwt.secret=whitefoxSuperSecureJwtSecretKey2026@123
server.port=8080
razorpay.key_id=YOUR_KEY_ID
razorpay.key_secret=YOUR_KEY_SECRET